noinst_LIBRARIES = libcontrib.a

libcontrib_a_SOURCES =

AM_CXXFLAGS =			\
    $(QT_CXXFLAGS)		\
    -Wall -W

libcontrib_a_SOURCES +=		\
    zip/unzip_p.h		\
    zip/unzip.cpp		\
    zip/unzip.h			\
    zip/zip_p.h			\
    zip/zip.cpp			\
    zip/zip.h			\
    zip/zipentry_p.h

EXTRA_DIST +=			\
    zip/README
