/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "sc3prefs.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window (void)
{
  GtkWidget *window;
  GtkWidget *page;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *table1;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *command;
  GtkWidget *working_dir;
  GtkWidget *working_dir_browse;
  GtkWidget *command_browse;
  GtkWidget *label12;
  GtkWidget *help_dir;
  GtkWidget *help_dir_browse;
  GtkWidget *label5;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window), _("window"));

  page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (page);
  gtk_container_add (GTK_CONTAINER (window), page);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (page), frame1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 3);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 3, 3, 3);

  table1 = gtk_table_new (3, 3, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (alignment1), table1);

  label6 = gtk_label_new (_("Sclang command line: "));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  label7 = gtk_label_new (_("SC3 working directory: "));
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  command = gtk_entry_new ();
  gtk_widget_show (command);
  gtk_table_attach (GTK_TABLE (table1), command, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, command, _("GAP command line"), NULL);

  working_dir = gtk_entry_new ();
  gtk_widget_show (working_dir);
  gtk_table_attach (GTK_TABLE (table1), working_dir, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, working_dir, _("Directory where gap is started from"), NULL);

  working_dir_browse = gtk_button_new_with_mnemonic (_("Browse..."));
  gtk_widget_show (working_dir_browse);
  gtk_table_attach (GTK_TABLE (table1), working_dir_browse, 2, 3, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (working_dir_browse), FALSE);

  command_browse = gtk_button_new_with_mnemonic (_("Browse..."));
  gtk_widget_show (command_browse);
  gtk_table_attach (GTK_TABLE (table1), command_browse, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (command_browse), FALSE);

  label12 = gtk_label_new (_("Help path: "));
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table1), label12, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  help_dir = gtk_entry_new ();
  gtk_widget_show (help_dir);
  gtk_table_attach (GTK_TABLE (table1), help_dir, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, help_dir, _("Directory where gap is started from"), NULL);

  help_dir_browse = gtk_button_new_with_mnemonic (_("Browse..."));
  gtk_widget_show (help_dir_browse);
  gtk_table_attach (GTK_TABLE (table1), help_dir_browse, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label5 = gtk_label_new (_("Sclang"));
  gtk_widget_show (label5);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label5);

  g_signal_connect ((gpointer) command, "moo_prefs_key",
                    G_CALLBACK (SC3_PREFS_SCLANG_COMMAND),
                    NULL);
  g_signal_connect ((gpointer) working_dir, "moo_prefs_key",
                    G_CALLBACK (SC3_PREFS_SCLANG_WORKING_DIR),
                    NULL);
  g_signal_connect ((gpointer) help_dir, "moo_prefs_key",
                    G_CALLBACK (SC3_PREFS_HELP_DIR),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window, window, "window");
  GLADE_HOOKUP_OBJECT (window, page, "page");
  GLADE_HOOKUP_OBJECT (window, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (window, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window, table1, "table1");
  GLADE_HOOKUP_OBJECT (window, label6, "label6");
  GLADE_HOOKUP_OBJECT (window, label7, "label7");
  GLADE_HOOKUP_OBJECT (window, command, "command");
  GLADE_HOOKUP_OBJECT (window, working_dir, "working_dir");
  GLADE_HOOKUP_OBJECT (window, working_dir_browse, "working_dir_browse");
  GLADE_HOOKUP_OBJECT (window, command_browse, "command_browse");
  GLADE_HOOKUP_OBJECT (window, label12, "label12");
  GLADE_HOOKUP_OBJECT (window, help_dir, "help_dir");
  GLADE_HOOKUP_OBJECT (window, help_dir_browse, "help_dir_browse");
  GLADE_HOOKUP_OBJECT (window, label5, "label5");
  GLADE_HOOKUP_OBJECT_NO_REF (window, tooltips, "tooltips");

  return window;
}

