AUTOMAKE_OPTIONS = dist-bzip2 no-dist-gzip
ACLOCAL_AMFLAGS = -I m4 $(ACLOCAL_FLAGS)

SUBDIRS = contrib moows ggap

EXTRA_DIST +=		\
    autogen.sh		\
    moo-debug.h		\
    moo-macros.h	\
    moo-pimpl.h		\
    moo-unit-tests.h	\
    COPYING		\
    THANKS

include mac/Makefile.incl
include win32/Makefile.incl
