#!/usr/bin/env python

import sys

TEMPLATE = 'html.tmpl'
NAME_PLACEHOLDER = 'DOC_FILE_NAME'

if not sys.argv[1:]:
    sys.stderr.write("Usage: %s <classname>" % (sys.argv[0],))
    sys.exit(1)

f = open(TEMPLATE)
text = f.read()
f.close()

output = text.replace(NAME_PLACEHOLDER, sys.argv[1], 1)
sys.stdout.write(output)

sys.exit(0)
