#!/usr/bin/env python

import sys
from manual import chapters

TEMPLATE = 'html.tmpl'
CHAPTER_FILE_NAME = 'CHAPTER_FILE_NAME'
CHAPTER_TITLE = 'CHAPTER_TITLE'

name = sys.argv[1]

file = open(TEMPLATE)
text = file.read()
file.close()

output = text.replace(CHAPTER_FILE_NAME, name, 1)
output = output.replace(CHAPTER_TITLE, chapters[name], 1)
sys.stdout.write(output)
