#!/usr/bin/env python

import sys
from manual import chap_titles

CHAPTER_FILE_NAME = 'CHAPTER_FILE_NAME'
CHAPTER_TITLE = 'CHAPTER_TITLE'

type = sys.argv[1]
name = sys.argv[2]

file = open(type + ".tmpl")
text = file.read()
file.close()

output = text.replace(CHAPTER_FILE_NAME, name, 1)
output = output.replace(CHAPTER_TITLE, chap_titles[name], 1)
sys.stdout.write(output)
