/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "gapprefs.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window (void)
{
  GtkWidget *window;
  GtkWidget *page;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *table1;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *command;
  GtkWidget *working_dir;
  GtkWidget *working_dir_browse;
  GtkWidget *command_browse;
  GtkWidget *label5;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *table2;
  GtkWidget *load_workspace;
  GtkWidget *load_workspace_entry;
  GtkWidget *load_workspace_browse;
  GtkWidget *save_workspace;
  GtkWidget *label10;
  GtkWidget *frame3;
  GtkWidget *alignment3;
  GtkWidget *table3;
  GtkWidget *init_pkg;
  GtkWidget *label11;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window), _("window"));

  page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (page);
  gtk_container_add (GTK_CONTAINER (window), page);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (page), frame1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 3);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 3, 3, 3);

  table1 = gtk_table_new (2, 3, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (alignment1), table1);

  label6 = gtk_label_new (_("GAP Command Line: "));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  label7 = gtk_label_new (_("GAP Working Dir: "));
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  command = gtk_entry_new ();
  gtk_widget_show (command);
  gtk_table_attach (GTK_TABLE (table1), command, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, command, _("GAP command line"), NULL);

  working_dir = gtk_entry_new ();
  gtk_widget_show (working_dir);
  gtk_table_attach (GTK_TABLE (table1), working_dir, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, working_dir, _("Directory where gap is started from"), NULL);

  working_dir_browse = gtk_button_new_with_mnemonic (_("Browse..."));
  gtk_widget_show (working_dir_browse);
  gtk_table_attach (GTK_TABLE (table1), working_dir_browse, 2, 3, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (working_dir_browse), FALSE);

  command_browse = gtk_button_new_with_mnemonic (_("Browse..."));
  gtk_widget_show (command_browse);
  gtk_table_attach (GTK_TABLE (table1), command_browse, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (command_browse), FALSE);

  label5 = gtk_label_new (_("GAP"));
  gtk_widget_show (label5);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label5);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (page), frame2, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 3);
  gtk_widget_set_sensitive (frame2, FALSE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 3, 3, 3);

  table2 = gtk_table_new (2, 3, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (alignment2), table2);

  load_workspace = gtk_check_button_new_with_mnemonic (_("Load Workspace On Startup "));
  gtk_widget_show (load_workspace);
  gtk_table_attach (GTK_TABLE (table2), load_workspace, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (load_workspace), FALSE);

  load_workspace_entry = gtk_entry_new ();
  gtk_widget_show (load_workspace_entry);
  gtk_table_attach (GTK_TABLE (table2), load_workspace_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (load_workspace_entry, FALSE);

  load_workspace_browse = gtk_button_new_with_mnemonic (_("Browse..."));
  gtk_widget_show (load_workspace_browse);
  gtk_table_attach (GTK_TABLE (table2), load_workspace_browse, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (load_workspace_browse, FALSE);
  gtk_button_set_focus_on_click (GTK_BUTTON (load_workspace_browse), FALSE);

  save_workspace = gtk_check_button_new_with_mnemonic (_("Save Workspace On Exit "));
  gtk_widget_show (save_workspace);
  gtk_table_attach (GTK_TABLE (table2), save_workspace, 0, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (save_workspace, FALSE);
  gtk_button_set_focus_on_click (GTK_BUTTON (save_workspace), FALSE);

  label10 = gtk_label_new (_("Workspace"));
  gtk_widget_show (label10);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label10);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (page), frame3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 3);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (frame3), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 0, 3, 3, 3);

  table3 = gtk_table_new (1, 1, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (alignment3), table3);

  init_pkg = gtk_check_button_new_with_mnemonic (_("Init GGAP Package On Startup "));
  gtk_widget_show (init_pkg);
  gtk_table_attach (GTK_TABLE (table3), init_pkg, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (init_pkg), FALSE);

  label11 = gtk_label_new (_("GGAP Package"));
  gtk_widget_show (label11);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label11);

  g_signal_connect ((gpointer) command, "moo_prefs_key",
                    G_CALLBACK (GAP_PREFS_GAP_COMMAND),
                    NULL);
  g_signal_connect ((gpointer) working_dir, "moo_prefs_key",
                    G_CALLBACK (GAP_PREFS_GAP_WORKING_DIR),
                    NULL);
  g_signal_connect ((gpointer) load_workspace, "moo_prefs_key",
                    G_CALLBACK (GAP_PREFS_GAP_LOAD_WORKSPACE),
                    NULL);
  g_signal_connect ((gpointer) load_workspace_entry, "moo_prefs_key",
                    G_CALLBACK (GAP_PREFS_GAP_WORKSPACE),
                    NULL);
  g_signal_connect ((gpointer) load_workspace_entry, "moo_sensitive",
                    G_CALLBACK (load_workspace),
                    NULL);
  g_signal_connect ((gpointer) load_workspace_browse, "moo_sensitive",
                    G_CALLBACK (load_workspace),
                    NULL);
  g_signal_connect ((gpointer) save_workspace, "moo_prefs_key",
                    G_CALLBACK (GAP_PREFS_GAP_SAVE_WORKSPACE),
                    NULL);
  g_signal_connect ((gpointer) save_workspace, "moo_sensitive",
                    G_CALLBACK (load_workspace),
                    NULL);
  g_signal_connect ((gpointer) init_pkg, "moo_prefs_key",
                    G_CALLBACK (GAP_PREFS_GAP_INIT_PKG),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window, window, "window");
  GLADE_HOOKUP_OBJECT (window, page, "page");
  GLADE_HOOKUP_OBJECT (window, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (window, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window, table1, "table1");
  GLADE_HOOKUP_OBJECT (window, label6, "label6");
  GLADE_HOOKUP_OBJECT (window, label7, "label7");
  GLADE_HOOKUP_OBJECT (window, command, "command");
  GLADE_HOOKUP_OBJECT (window, working_dir, "working_dir");
  GLADE_HOOKUP_OBJECT (window, working_dir_browse, "working_dir_browse");
  GLADE_HOOKUP_OBJECT (window, command_browse, "command_browse");
  GLADE_HOOKUP_OBJECT (window, label5, "label5");
  GLADE_HOOKUP_OBJECT (window, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (window, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window, table2, "table2");
  GLADE_HOOKUP_OBJECT (window, load_workspace, "load_workspace");
  GLADE_HOOKUP_OBJECT (window, load_workspace_entry, "load_workspace_entry");
  GLADE_HOOKUP_OBJECT (window, load_workspace_browse, "load_workspace_browse");
  GLADE_HOOKUP_OBJECT (window, save_workspace, "save_workspace");
  GLADE_HOOKUP_OBJECT (window, label10, "label10");
  GLADE_HOOKUP_OBJECT (window, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (window, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window, table3, "table3");
  GLADE_HOOKUP_OBJECT (window, init_pkg, "init_pkg");
  GLADE_HOOKUP_OBJECT (window, label11, "label11");
  GLADE_HOOKUP_OBJECT_NO_REF (window, tooltips, "tooltips");

  return window;
}

